# Generated by Django 4.0.4 on 2022-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='input surname author', max_length=100, verbose_name='Фамилия автора'),
        ),
    ]
